twist_mux:
  ros__parameters:
    topics:
      controller:
        topic   : controller/cmd_vel
        timeout : 0.5
        priority: 10
      keyboard:
        topic   : keyboard/cmd_vel
        timeout : 0.5
        priority: 9
      hololens:
        topic   : hololens/cmd_vel
        timeout : 0.5
        priority: 8
      navStack:
        topic   : nav_stack/cmd_vel
        timeout : 0.5
        priority: 7