<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>spot_bringup</name>
  <version>1.0.0</version>
  <description>
    Bringup package for Boston Dynamics Spot.
  </description>

  <maintainer email="blakeanderson@utexas.edu">Blake Anderson</maintainer>
  <author email="blakeanderson@utexas.edu">Blake Anderson</author>

  <license>Proprietary</license>

  <exec_depend>velodyne</exec_depend>
  <exec_depend>spot_driver</exec_depend>
  <exec_depend>spot_navigation</exec_depend>
  <exec_depend>spot_description</exec_depend>
  <exec_depend>spot_manipulation_driver</exec_depend>
  <exec_depend>joy</exec_depend>
  <exec_depend>teleop_twist_joy</exec_depend>
  <exec_depend>realsense2_camera</exec_depend>
  <exec_depend>joy_linux</exec_depend>
  <exec_depend>depth_image_proc</exec_depend>
  <exec_depend>twist_mux</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
